// Generated by CoffeeScript 1.7.1
var exhibia;

exhibia = {
  renderEmoticons: function(message) {
    var emoticon, emoticonUrl, image, textToEmoticon;
    emoticonUrl = '/static/img/emoticons/';
    textToEmoticon = {
      ":'(": 'Crying.png',
      ":''(": 'Crying2.png',
      ">:)": 'Devil.png',
      ':P~': 'Drooling.png',
      "<3": 'Heart.png',
      ':X': 'Not-Talking.png',
      'O:)': 'Sacred.png',
      ':)': 'smile.png',
      ':(': 'Sad.png',
      ':|': 'Straight-Face.png',
      ':P': 'Tongue.png',
      ';)': 'Winking.png',
      ':D': 'Big-Grin.png',
      '_b': 'Cool.png'
    };
    if (typeof message === 'string') {
      for (emoticon in textToEmoticon) {
        image = textToEmoticon[emoticon];
        message = message.replace(emoticon, "<img src='" + emoticonUrl + textToEmoticon[emoticon] + "' alt='" + image + "'/>");
      }
      return message;
    } else {
      throw "Message string not provided";
    }
  }
};

$(document).ready(function() {
  var comment, _i, _len, _ref;
  _ref = $('div.comment');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    comment = _ref[_i];
    $(comment).html(exhibia.renderEmoticons($(comment).html()));
  }
  if (typeof location.hash !== 'undefined' && location.hash === '#_-_') {
    return $.get('/exhibit/tracking-code/', {
      service_provider: 'facebook'
    }, function(data) {
      return $(data).find('script:first').appendTo('body');
    });
  }
});
